function createfigure(X1, Y1, X2, Y2, X3, Y3)
%CREATEFIGURE(X1, Y1, X2, Y2, X3, Y3)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data
%  X3:  vector of x data
%  Y3:  vector of y data

%  Auto-generated by MATLAB on 11-Apr-2016 20:55:03

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create datetime plot
plot(X1,Y1,'DisplayName','Original data','MarkerSize',20,'Marker','.',...
    'LineWidth',0.75);

% Create datetime plot
plot(X2,Y2,'DisplayName','Preprocessed data (local maxima/minima)',...
    'MarkerSize',20,...
    'Marker','.',...
    'LineWidth',0.75);

% Create datetime plot
plot(X3,Y3,'DisplayName','Processed data (turning points)','MarkerSize',20,...
    'Marker','.',...
    'LineWidth',0.75);

box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontSize',14,'XGrid','on');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.65752552028446 0.163840313676364 0.216785714285714 0.0897858319604613],...
    'FontSize',14);

